service: flowbite_components
image: coderberry/flowbite_components

registry:
  username: coderberry
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY

servers:
  web:
    hosts:
      - 195.201.128.126
    labels:
      traefik.http.routers.flowbite_components.entrypoints: websecure
      traefik.http.routers.flowbite_components.rule: "Host(`flowbitecomponents.org`) || Host(`www.flowbitecomponents.org`)"
      traefik.http.routers.flowbite_components.tls.certresolver: letsencrypt

traefik:
  options:
    publish:
      - "443:443"
    volume:
      - "/letsencrypt/acme.json:/letsencrypt/acme.json"
  args:
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
    entryPoints.web.http.redirections.entryPoint.to: websecure # We want to force https
    entryPoints.web.http.redirections.entryPoint.scheme: https
    entryPoints.web.http.redirections.entrypoint.permanent: true
    certificatesResolvers.letsencrypt.acme.email: "admin@flowbitecomponents.org"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json" # Must match the path in `volume`
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web
